### PR TITLE
Adding toMap() function.

### PR DESCRIPTION
**Pull request by ThinkDigitalSoftware**
added a public method to convert the contact to a map using the existing static _toMap(Contact contact) function.

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
Added a note field, but someone needs to add the actual adding to the phone.

**Comment by clovisnicolas** [comment]
Notes still have to be added to the Android contacts

**Comment by ThinkDigitalSoftware** [comment]
?

**Comment by ThinkDigitalSoftware** [comment]
I see them in there?

**Comment by clovisnicolas** [comment]
No, as you previously said, they still have to be actually added to the phone.

**Comment by ThinkDigitalSoftware** [comment]
Ok. I'm just trying to understand why you commented that since I already
commented that.

**Comment by ThinkDigitalSoftware** [comment]
I thought you were referring to the Java Contact class.

**Comment by clovisnicolas** [comment]
If anyone feels like actually saving the notes to the phone please do, and I will merge this asap

**Comment by ThinkDigitalSoftware** [comment]
When you say this, you're referring to saving it to the contact, right?
Just double checking.

**Comment by clovisnicolas** [comment]
Yes, when adding and when fetching a contact, in the class ContactsServicePlugin.java, in the methods 
- getContactsFrom 
--> The contact's notes should be fetched
- addContact 
--> The contact's notes should be updated

The idea is to do what has been done for other fields, but for this one as well
https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Note

**Comment by ThinkDigitalSoftware** [comment]
Understood. I'm researching it now.

**Comment by lambasoft** [comment]
Yo Any update guys?

**Pull request merged**
